# This playbook automates the build and deployment process for the Flask application
---
- name: Build and deploy Flask application
  # Using localhost for simplified deployment - alternatively could use remote hosts
  hosts: localhost
  connection: local
  gather_facts: false
  
  # Variables defined here instead of vars/ directory for simplicity
  vars:
    app_name: formlabs-app
    docker_tag: latest
    helm_release: formlabs-release
    helm_chart: ./formlabs-chart

  tasks:
    - name: Build Docker image (includes running tests)
      community.docker.docker_image:
        name: "{{ app_name }}"
        tag: "{{ docker_tag }}"
        source: build
        build:
          path: .
          pull: yes  # Always pull latest base images for security
        state: present
        force_source: yes  # Ensure rebuild even if image exists
      register: build_result

    - name: Deploy to Kubernetes using Helm
      kubernetes.core.helm:
        name: "{{ helm_release }}"
        chart_ref: "{{ helm_chart }}"
        release_namespace: default
        create_namespace: true
        values:
          image:
            repository: "{{ app_name }}"
            tag: "{{ docker_tag }}"
      # Only deploy if build succeeds, maintaining system integrity
      when: build_result is success
